using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using WpfAppBindings.models;

#nullable enable

namespace WpfAppBindings.Viewmodel
{
    public class MainViewmodel : INotifyPropertyChanged
    {
        // Het viewmodel gebruiken we als een soort van "brug" tussen de view (UI) en de data.
        // Een viewmodel bevat de logica en de data die de view nodig heeft om correct te functioneren.
        // In dit geval hebben we een eenvoudige property genaamd MyProperty die we willen 'binden' aan een element in de UI, zoals een TextBlock of een Label.

        private int? _personsloaded;
        private ObservableCollection<Person>? _persons;
        private Person? _selectedperson;

        // constructor
        public MainViewmodel()
        {
            _personsloaded = 0;
            _persons = new ObservableCollection<Person>();
            // inladen van personen bij het aanmaken van het viewmodel
            getPersons();
        }


        public int? PersonsLoaded
        {
            get { return _personsloaded; }
            set
            {
                _personsloaded = value;
                OnPropertyChanged(nameof(PersonsLoaded));
            }
        }


        #region INotifyPropertyChanged Implementation

        // De INotifyPropertyChanged interface is essentieel voor data binding in WPF.
        // Zonder deze interface zou de UI niet weten wanneer een property in het viewmodel is gewijzigd, en zou dus niet automatisch worden bijgewerkt.
        // Wanneer een property in het viewmodel wordt gewijzigd, roept de setter van die property de OnPropertyChanged methode aan, die op zijn beurt het PropertyChanged event triggert.

        public event PropertyChangedEventHandler? PropertyChanged;
        private void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion


        // get Persons from REST API
        public ObservableCollection<models.Person>? Persons
        {
            get { return _persons; }
            set
            {
                _persons = value;
                OnPropertyChanged(nameof(Persons));
            }
        }


        public Person? SelectedPerson
        {
            get { return _selectedperson; }
            set
            {
                _selectedperson = value;
                OnPropertyChanged(nameof(SelectedPerson));
            }
        }

        public void getPersons()
        {
            // call rest API
            // to get person data and populate the Persons collection
            using (var client = new HttpClient())
            {

                try
                {
                    var response = client.GetAsync("http://localhost:8888/api/person").Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var json = response.Content.ReadAsStringAsync().Result;
                        // Deserialize json to ObservableCollection<Person> and assign to Persons property

                        // Om JSONConvert te laten werken, moeten we de Newtonsoft.Json package installeren via NuGet Package Manager.
                        Persons = JsonConvert.DeserializeObject<ObservableCollection<models.Person>>(json);

                    }
                }
                catch (Exception ex)
                {
                    // Handle exceptions (e.g., network errors, JSON parsing errors)
                    Console.WriteLine($"Error fetching persons: {ex.Message}");
                    // create dummy data for testing purposes
                    Persons = new ObservableCollection<models.Person>
                    {
                        new models.Person(1, "John Doe", 30),
                        new models.Person(2, "Jane Smith", 25),
                        new models.Person(3, "Bob Johnson", 40)
                    };
                }
                PersonsLoaded = Persons.Count;



            }

        }


        public void addPerson(Person person)
        {

            // only name and age are required in the JSON body, the id will be generated by the server



            // call rest API to add person
            using (var client = new HttpClient())
            {
                try
                {
                    var json = JsonConvert.SerializeObject(new { name = person.name, age = person.age });
                    var content = new StringContent(json, Encoding.UTF8, "application/json");
                    var response = client.PostAsync("http://localhost:8888/api/person", content).Result;
                    if (response.IsSuccessStatusCode)
                    {
                        // If the POST request is successful, we can add the new person to the Persons collection.
                        Persons.Add(person);
                        PersonsLoaded = Persons.Count; // Update the count of loaded persons
                    }
                }
                catch (Exception ex)
                {
                    // Handle exceptions (e.g., network errors, JSON parsing errors)
                    Console.WriteLine($"Error adding person: {ex.Message}");
                }
            }
        }


    }
}

